### ISSUE TITLE
Cannot import after pip install

### ISSUE THREAD

**Issue by Wbec** [coin-or/rbfopt#18]
After installing rbfopt with pip, I get the following error.
```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rbfopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/civil/.local/lib/python3.6/site-packages/rbfopt/__init__.py", line 6, in <module>
    from .rbfopt_algorithm import RbfoptAlgorithm
  File "/home/civil/.local/lib/python3.6/site-packages/rbfopt/rbfopt_algorithm.py", line 27, in <module>
    import rbfopt.rbfopt_aux_problems as aux
  File "/home/civil/.local/lib/python3.6/site-packages/rbfopt/rbfopt_aux_problems.py", line 22, in <module>
    import pyomo.environ
ModuleNotFoundError: No module named 'pyomo'
```
Pyomo was already installed and rerunning the import yields:
```
>>> import rbfopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/civil/.local/lib/python3.6/site-packages/rbfopt/__init__.py", line 6, in <module>
    from .rbfopt_algorithm import RbfoptAlgorithm
  File "/home/civil/.local/lib/python3.6/site-packages/rbfopt/rbfopt_algorithm.py", line 26, in <module>
    import rbfopt.rbfopt_utils as ru
AttributeError: module 'rbfopt' has no attribute 'rbfopt_utils'
```
These errors were directly one after the other in an interactive session.
I have verified that rbfot_utils.py is in `~/.local/lib/python3.6/site-packages/rbfopt`

**Comment by Wbec** [comment]
`!pip install --user --upgrade --force-reinstall rbfopt` ended up fixing things. (I found that while trying to add more info) Sorry for the unnecessary issue.
