### ISSUE TITLE
Tests never finish, stuck on "Solving hartman6 with random seed 512319876"

### ISSUE THREAD

**Issue by aanderse** [coin-or/rbfopt#44]
I have successfully compiled `rbfopt` for my GNU/Linux distro. When I attempt to run the tests they never finish, always getting stuck here:

```
Solving hartman6 with random seed 512319876
  Iter  Cycle  Action             Objective value      Time      Gap
  ----  -----  ------             ---------------      ----      ---
     0      0  Initialization           -0.001120      0.02    84.79  
     0      0  Initialization           -0.481835      0.02    84.79  
     0      0  Initialization           -0.129858      0.02    84.79  
     0      0  Initialization           -0.013445      0.02    84.79  
     0      0  Initialization           -0.505315      0.02    84.79 *
     0      0  RefinementStep           -0.130395      0.23    84.79
```

I tried the [Minimal working example](https://github.com/coin-or/rbfopt#minimal-working-example) and it runs without issue so I'm not sure what the problem is.

Any help is greatly appreciated.

**Comment by gnannicini** [comment]
Are the solvers bonmin/ipopt installed and available from the directory
where you launch the tests? Or do they only work if you specify the path?
I have never seen this behavior: it is supposed to tell you which tests
fail. If the test does not make any progress, try interrupting it with
Ctrl+C until you get a proper error message to identify where the problem
is.

**Comment by aanderse** [comment]
> try interrupting it with Ctrl+C until you get a proper error message to identify where the problem is.

This is what I saw...
```
Solving hartman6 with random seed 512319876
  Iter  Cycle  Action             Objective value      Time      Gap
  ----  -----  ------             ---------------      ----      ---
     0      0  Initialization           -0.001120      0.02    84.79  
     0      0  Initialization           -0.481835      0.02    84.79  
     0      0  Initialization           -0.129858      0.02    84.79  
     0      0  Initialization           -0.013445      0.02    84.79  
     0      0  Initialization           -0.505315      0.02    84.79 *
     0      0  RefinementStep           -0.130395      0.23    84.79  
^C
----------------------------------------------------------------------
Ran 54 tests in 125.435s

OK
Traceback (most recent call last):
  File "/nix/store/2wh11hqr881gpp5xkc3r4l91h42k0zl9-python3.9-nose2-0.11.0/bin/.nose2-wrapped", line 9, in <module>
    sys.exit(discover())
  File "/nix/store/ykpdlvr22h64f1skpi56fkqrsp24s1sy-python3-3.9.10-env/lib/python3.9/site-packages/nose2/main.py", line 339, in discover
    return main(*args, **kwargs)
  File "/nix/store/ykpdlvr22h64f1skpi56fkqrsp24s1sy-python3-3.9.10-env/lib/python3.9/site-packages/nose2/main.py", line 87, in __init__
    super(PluggableTestProgram, self).__init__(**kw)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/nix/store/ykpdlvr22h64f1skpi56fkqrsp24s1sy-python3-3.9.10-env/lib/python3.9/site-packages/nose2/main.py", line 302, in runTests
    self.result = runner.run(self.test)
  File "/nix/store/ykpdlvr22h64f1skpi56fkqrsp24s1sy-python3-3.9.10-env/lib/python3.9/site-packages/nose2/runner.py", line 55, in run
    executor(test, result)
  File "/nix/store/ykpdlvr22h64f1skpi56fkqrsp24s1sy-python3-3.9.10-env/lib/python3.9/site-packages/nose2/runner.py", line 43, in executor
    return suite(result)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/case.py", line 651, in __call__
    return self.run(*args, **kwds)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/aaron/work/tvbeat/rbfopt/tests/test_rbfopt_algorithm.py", line 110, in test_time_limit
    res = alg.optimize()
  File "/home/aaron/work/tvbeat/rbfopt/src/rbfopt/rbfopt_algorithm.py", line 791, in optimize
    self.optimize_parallel(pause_after_iters)
  File "/home/aaron/work/tvbeat/rbfopt/src/rbfopt/rbfopt_algorithm.py", line 1755, in optimize_parallel
    pool.join()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/multiprocessing/pool.py", line 662, in join
    self._worker_handler.join()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/threading.py", line 1053, in join
    self._wait_for_tstate_lock()
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/threading.py", line 1073, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
```

I'm not familiar with the code here so it is a bit hard for me to guess what the issue is. Any thoughts? Any and all help is greatly appreciated :bow:

**Comment by gnannicini** [comment]
Yes, there seems to be a problem with running the optimization on parallel
threads. Judging from this stack trace, the algorithm is done, and is
waiting for all threads to conclude before returning control to the caller
with a successful optimization result. However, it seems that some of the
threads do not conclude. I am not sure why this happens. I suspect your
code will work fine in serial mode. Try independently checking if Python's
multiprocessing is working as intended on your machine. In the meantime,
I'll see if some possible cause comes to mind.

**Comment by gnannicini** [comment]
These errors indicate that some of the search subroutines are not
returning the right value -- in fact, they are not returning a point
at all.
I suspect this is a problem with the solvers, and it may have been the
cause of the previous errors during parallel optimization.
(OMP_NUM_THREADS has nothing to do with this -- RBFOpt has its own
parallel capabilities, set by the parameter num_cpus.)
Would it be difficult for you to have bonmin and ipopt in the path?
E.g. /usr/local/bin. That may fix things.

**Comment by aanderse** [comment]
> I suspect this is a problem with the solvers

Looks like you are correct. I had been testing with an `ipopt` and `bonmin` that I compiled myself when I got these errors. I just swapped my builds with binaries I downloaded from https://ampl.com/products/solvers/open-source/ and everything worked.

Is there any information you can give me so I can open a ticket against the `ipopt` issue tracker which might be helpful? I built `ipopt` and `bonmin` linking against what Debian calls `libamplsolver` (sourced [here](https://ampl.com/netlib/ampl/)).

Thank you **very** much for your help.

**Comment by gnannicini** [comment]
Sorry, I don't know what is the problem with your ipopt installation. You
do need to link against the ASL (AMPL solver library), so that the
executables accept the AMPL .nl format (pyomo needs it, and RBFOpt relies
on pyomo). I have compiled it many times from source, but I am not sure how
Debian's libamplsolver library changes that process.

Glad to know that things are working, in any case.

**Comment by aanderse** [comment]
@gnannicini I apologize but it looks like in the massive matrix of experiments I was running to determine the cause of my problem I got confused... I still have an issue related to parallel threads.

When I use provided `bonmin` and `ipopt` binaries the tests still hang... unless I pass `OMP_NUM_THREADS=1` on the command line. If I pass `OMP_NUM_THREADS=1` then the tests always finish regardless of whether I use provided binaries or my own (the tests finish and fail if I use my own, but that is a separate issue).

**The tests actually finish and pass if I use the provided binaries... but only if I set `OMP_NUM_THREADS=1`.**

I know you said that `OMP_NUM_THREADS` shouldn't cause that issue, but at least in some way this environment variable is having impact on running the tests.

Any thoughts?

Again, thank you :bow:

**Comment by gnannicini** [comment]
You might be onto something. Thanks for pointing this out.
If it is not too complicated, could you check what happens if in the
tests/test_* files you change the order of imports so that rbfopt is
imported *before* numpy, and try again if your tests still get stuck?

**Comment by aanderse** [comment]
Sorry for the delay.

I called `nose2` to run the tests before and after making modifications you mentioned. As you suspected the test succeeded after your suggested changes.

For reference the command I ran:

`env PATH=/nix/store/hgxnv9cvskgnmsridp87lncigl9sc1ih-bonmin-1.8.8/bin:/nix/store/4lw2ihyaq4jav0ldrmi0andf9fqam5gf-ipopt-3.12.13/bin/:$PATH /nix/store/16x68xkx4v26yimkzxv0ypnkrpgc6h8h-python3-3.9.9-env/bin/nose2`

For reference the changes I applied:

https://github.com/aanderse/rbfopt/commit/c6d07efa8f170244d1d23353567d3553bdb7bbdd

**Comment by gnannicini** [comment]
The most recent commits (and the corresponding release) change the order of imports during tests. This should automatically set OMP_NUM_THREADS=1 during tests, avoiding the issue that you experienced. Unfortunately I don't know of any other way to fix this issue with OpenBLAS.

**Comment by aanderse** [comment]
Thanks @gnannicini!
